### ISSUE TITLE
what else?

### ISSUE THREAD

**Issue by Polonium8400** [CoderDojoBallaghaderreen/python-projects#12]
What else can I work on during the week?

**Comment by theycallmemac** [comment]
Hey Jaime. At CoderDojo today I want you to teach Pierce a little about GitHub, and set him up on it. Then help him fork this repo. This will be good revision for you too. 

Once has has forked the report I want you to teach him how calc.py works. After that, I want him to make a change to calc.py, it can be anything from changing a variable name to adding a doubling function! 

After this if you guys have time I want you to have a look at loopy.py and try understand what it does. After this, I'd like you to write a program using a loop that returns the sum of all the number less than 5. 

If you don't get all this done today that's okay, it can be for during the week as well!

**Comment by Polonium8400** [comment]
what is the theme that you created on atom as im going to download it

**Comment by theycallmemac** [comment]
pipboy-ui and pipboy-syntax - you need both :) I'm closing this as an issue now
