### ISSUE TITLE
Quick crash error

### ISSUE THREAD

**Issue by Polonium8400** [CoderDojoBallaghaderreen/python-projects#18]
although the project works , whenever i run it on atom (i recently downloaded it), the program runs the script and then when its done , it instantly crashes  , plz help

**Comment by theycallmemac** [comment]
can you send me a screenshot of what it shows you?

**Comment by Polonium8400** [comment]
would it have something to do with the Python IDLE settings?

**Comment by theycallmemac** [comment]
explain what you do when you try to run the script.

**Comment by Polonium8400** [comment]
i cant even screenshot as it ***instantly*** crashes

**Comment by theycallmemac** [comment]
What are you pressing/doing to try run it though?

**Comment by Polonium8400** [comment]
like i can run past the input for the sums and selections but it crashes before the answer can be shown

**Comment by Polonium8400** [comment]
im running through the file explorer/ start menu

**Comment by theycallmemac** [comment]
Currently when I try run the script i get this error:

```
  File "calc.py", line 9
    def add(x,y)
               ^
SyntaxError: invalid syntax
```

**Comment by theycallmemac** [comment]
You need to fix this first

**Comment by Polonium8400** [comment]
then the window showing the file closes itself

**Comment by Polonium8400** [comment]
ok will do on github and atom

**Comment by theycallmemac** [comment]
again, you need to fix the program first. I'm not sure why atom is crashing. I would write your code on atom for now and run it on the command line instead. Don;t try integrating anything just yet :)

**Comment by Polonium8400** [comment]
wait i have them all the functions set up right on the PR and atom

**Comment by Polonium8400** [comment]
well how do you get to the file from the CMD?

**Comment by theycallmemac** [comment]
So it would seem, apologies. I'm assuming you're using windows. You have to open Command Prompt (just search for it) and then navigate your way to where the python file is. Once you've found it type in ```python3 calc.py``` and it should run as normal!

If you cant figure out how to navigate your way around the filesystem, just save your python file in your home directory (that would be the folder your command prompt opens in!!!)

Let me know how you get on :)

**Comment by Polonium8400** [comment]
i cant work the CMD line plz help

**Comment by Polonium8400** [comment]
:confounded: this is hard

**Comment by theycallmemac** [comment]
When you open the prompt type in ```dir```

**Comment by theycallmemac** [comment]
that should show you everything in the current folder you are in

**Comment by Polonium8400** [comment]
ive found out how to get to find the file but i cant figure out how to run it

**Comment by Polonium8400** [comment]
ive been using  www.dummies.com/computers/operating-systems/windows-xp-vista/how-to-search-for-files-from-the-dos-command-prompt/

**Comment by Polonium8400** [comment]
but i cant figure out how to run it :/

**Comment by theycallmemac** [comment]
python3 calc.py

If that command doesnt work it means you have to download python3 form here https://www.python.org/downloads/release/python-363/

**Comment by Polonium8400** [comment]
and ive tryed ```python3 calc.py``` after the dir stuff

**Comment by Polonium8400** [comment]
and i have a python 3 IDLE

**Comment by Polonium8400** [comment]
![image](https://user-images.githubusercontent.com/33232119/33798794-f8da70ac-dd16-11e7-9c45-eb933cfff851.png)

**Comment by Polonium8400** [comment]
also your package on atom has this 'deprecation' call:
pipboy-syntax\index.less
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

.syntax => .syntax--syntax
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.
Report Issue

**Comment by theycallmemac** [comment]
Yeah I'm aware of the deprecation, I have found the time to fix it yet :P

**Comment by Polonium8400** [comment]
![image](https://user-images.githubusercontent.com/33232119/33799034-951b9df2-dd1b-11e7-998f-8ba59cd1842e.png)
i get this when i try the ```python 3 calc.py``` stuff

**Comment by theycallmemac** [comment]
do just the dir bit first.

then when you have entered that click the enter button and then enter the python command

**Comment by Polonium8400** [comment]
well in my last code like this the ```While True``` allowed the window to stay open and have the menu to open up again

**Comment by Polonium8400** [comment]
![image](https://user-images.githubusercontent.com/33232119/33806617-e574b534-ddc2-11e7-922e-482e066375d7.png)
with the ```while True:``` loop added the menu appears again and solves the error

**Comment by Polonium8400** [comment]
i won't add the ```while``` loop onto the repo code
