### ISSUE TITLE
create a evenodd.py file in loops folder

### ISSUE THREAD

**Issue by theycallmemac** [CoderDojoBallaghaderreen/python-projects#20]
This issue is for Pierce.

I'd like you to write a loop which runs ```n``` times, just like the previous loops you have written.

This loop must check if the current number, in this case that number is called ```i```,  is even or odd.

You will need to use control flow statements (if,else) within the loop.

HINT: if the remainder of a number divided by 2 is 0 then it is even. The symbol for the remainder is ```%```. 

Best of luck :)

**Comment by draegast** [comment]
yeah ok ill give it a go and see what i can come up with
