### ISSUE TITLE
use a loop in our calc.py file

### ISSUE THREAD

**Issue by theycallmemac** [CoderDojoBallaghaderreen/python-projects#21]
This issue is for Jamie. 

We need our calculator to run until we ask it to break. This basically means we will keep taking user input until the user decides they are finished.

I believe you've done something like this already. Push your changes when ready so we can use a while loop in our calculator :)

**Comment by Polonium8400** [comment]
Ok and you are alright to pin/mention me

**Comment by Polonium8400** [comment]
Done!
