### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Polonium8400** [CoderDojoBallaghaderreen/python-projects#24]
Can a while loop be set up to follow the conditions under a variable , like this:
```While mode == "verif"```

**Comment by theycallmemac** [comment]
You could use a loop like that. What do you pan to do with it?

**Comment by Polonium8400** [comment]
Possibly to add more modes or to add different languages or something like that

**Comment by Polonium8400** [comment]
Since the idea that the while loop will keep the mode on until changed

**Comment by theycallmemac** [comment]
That makes sense I suppose yes. I look forward to seeing what you can do with it :)

**Comment by Polonium8400** [comment]
Okay

**Comment by theycallmemac** [comment]
Can we called this closed or do you have any other questions on this ?

**Comment by Polonium8400** [comment]
No
