### ISSUE TITLE
Github Classrooms alternative

### ISSUE THREAD

**Issue by theycallmemac** [CoderDojoBallaghaderreen/python-projects#32]
Hey guys, so on further inspection Github classrooms isn't exactly an option as it we aren't linked with any university so it would be false to claim so. If you're not linked to a Uni then you have to may $9 per month per user, and we can't afford that.

I have a different idea. Soon, I'll be adding two new repositiores, python-classes and python-syllabus. I ask you to do nothing with them at all once they are added, don't fork/clone/edit them at all. If both of you could agree to this before I add the new repositories, that'd really put my mind at ease!

We are back on the 20th of January and I'll explain everything then and there.

**Comment by Polonium8400** [comment]
Oook

**Comment by draegast** [comment]
yeah alright
