### ISSUE TITLE
should we create a trello/the projects tab/wiki for the repo?

### ISSUE THREAD

**Issue by Polonium8400** [CoderDojoBallaghaderreen/python-projects#9]
my view is that Trello/Github Projects tab would help with communication and that and the wiki would help learners to understand the code

**Comment by theycallmemac** [comment]
This is a good idea. I could definitely write up something to help new users understand the different projects and how they work.

**Comment by Polonium8400** [comment]
Also would we need a better way of the "team" to communicate?

**Comment by theycallmemac** [comment]
Im unsure about that. I'd have to talk to the other CoderDojo mentors about if that's even possible. I don't think it is.

**Comment by Polonium8400** [comment]
ok

**Comment by Polonium8400** [comment]
i found this thing called utopian.io , although we it may not be viable , its a thing that can be used to make money from commiting to github

**Comment by theycallmemac** [comment]
I'll have a look into it now :)
